/* Write your PL/SQL query statement below */

SELECT P.PRODUCT_ID, 
COALESCE(ROUND(SUM((U.UNITS * P.PRICE))/SUM(U.UNITS),2),0) AS AVERAGE_PRICE
FROM PRICES P
LEFT JOIN UNITSSOLD U ON U.PRODUCT_ID = P.PRODUCT_ID AND U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID;

