/* Write your PL/SQL query statement below */
SELECT U.NAME, T.BALANCE
FROM USERS U
JOIN (SELECT ACCOUNT, SUM(AMOUNT) AS BALANCE FROM TRANSACTIONS GROUP BY ACCOUNT) T
ON T.ACCOUNT = U.ACCOUNT
WHERE T.BALANCE > 10000; 