/* Write your PL/SQL query statement below */
SELECT query_name,
    ROUND(SUM(RATING/POSITION)/COUNT(POSITION),2) AS quality,
    ROUND(AVG(CASE WHEN RATING < 3 THEN 1.0 ELSE 0.0 END)*100,2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES 
WHERE QUERY_NAME IS NOT NULL
GROUP BY QUERY_NAME;
